# Generated by Django 3.1.3 on 2023-08-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230809_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='grade',
        ),
    ]
