# Generated by Django 3.1.3 on 2023-08-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_question_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='selected_ids',
            new_name='selected_id',
        ),
    ]
